# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# --- atmega328p on breadboard
BOARD_TAG    = uno
ISP_PROG     = usbtiny
AVRDUDE_OPTS = -v
ARDUINO_DIR  = /opt/arduino
ARDMK_DIR    = /usr/share/arduino

ARDUINO_LIBS = Adafruit_BluefruitLE_nRF51-master SPI SoftwareSerial

include /usr/share/arduino/Arduino.mk
